#   server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  application:
#    微服务名:product-data-service
    name: product-data-service
  zipkin:
#    zipkin url
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
#      eureka地址
      defaultZone: http://localhost:8761/eureka/