spring:
  application:
    name: config-server #微服务名:config-server
  cloud:
    config:
      label: master #分支:主分支
      server:
        git:
          uri: https://github.com/how2j/springcloudConfig/  #git地址
          searchPaths: respo  #目录
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #声明eureka地址