eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #eureka 地址
spring:
  application:
    name: product-view-service-feign  #微服务名:product-view-service-feign
  zipkin:
    base-url: http://localhost:9411 #zipkin 地址
#  thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5